CREATE TABLE contact_us
(
Contact_Id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
firstname VARCHAR(15) NOT NULL,
lastname VARCHAR(15) NOT NULL,
email_id VARCHAR(20) NOT NULL,
p_comment VARCHAR(50) NOT NULL
);
